title: Jonathan Kelly
position: Mathematics Student
affiliation: Trinity College Dublin
email: kellyj83@tcd.ie
keywords: minimal academic
#google_scholar: https://scholar.google.com/
github_link: https://github.com/kellyj83
linkedin: https://www.linkedin.com/in/jonathan-kelly-4b70121b3/
cv_link: ./files/cv.pdf
avatar: ./assets/img/photo.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
